# Generated by Django 5.1 on 2024-08-16 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Cultura')),
            ],
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True, verbose_name='CPF ou CNPJ')),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4, verbose_name='Tipo de Documento')),
                ('nome_produtor', models.CharField(max_length=255, verbose_name='Nome do Produtor')),
                ('nome_fazenda', models.CharField(max_length=255, verbose_name='Nome da Fazenda')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('area_total', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Área Total (ha)')),
                ('area_agricultavel', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Área Agricultável (ha)')),
                ('area_vegetacao', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Área de Vegetação (ha)')),
                ('culturas', models.ManyToManyField(to='produtor.cultura', verbose_name='Culturas')),
            ],
        ),
    ]
